### PR TITLE
Upgrade zap and fix url

### PR DESCRIPTION
**Pull request by dragonly**
1. upgrade zap to 1.19.0
2. fix unified log format doc url

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Thanks for your pull request @dragonly ! May I ask the reason you do the version bump?

**Comment by dragonly** [comment]
@tisonkun I am currently trying to optimize the general_log performance of tidb-server, and digged into some details of `zap`. I found some interesting enhancements in the following [releases](https://github.com/uber-go/zap/releases).

For example, in `v1.18.0`:
* https://github.com/uber-go/zap/pull/961: Add zapcore.BufferedWriteSyncer, a new WriteSyncer that buffers messages in-memory and flushes them periodically.

I haven't done a thorough research, but I believe we can do something later to enhance the logging performance of TiDB itself, by leveraging the enhancements of `zap`!

**Review by tisonkun — APPROVED** [review]
Thanks for your explanation. LGTM.

Though we're using our own WriteSyncer IIRC, we cannot make use of `zapcore.BufferedWriteSyncer` for free.

**Comment by dragonly** [comment]
> Though we're using our own WriteSyncer IIRC, we cannot make use of `zapcore.BufferedWriteSyncer` for free.

Actually we can wrap [this](https://github.com/pingcap/log/blob/master/log.go#L46) in a `zapcore.BufferedWriteSyncer`, and everything seems just work.

**Review by disksing — APPROVED** [review]

**Pull request merged**
